### ISSUE TITLE
Upgrade to php 8.1? Blocker for Carson

### ISSUE THREAD

**Issue by weaverryan** [Nyholm/git-reviewer#4]
Hi!

Could you upgrade this to work with PHP 8.1? We need it of carson is to use 8.1. Currently, if I update the deps, I receive this error:

> Uncaught TypeError: Github\HttpClient\Builder::__construct(): Argument #2 ($requestFactory) must be of type ?Psr\Http\Message\RequestFactoryInterface, Nyholm\Psr7\Factory\HttplugFactory given, called in /private/var/folders/ck/flmtvlh94bz_p8191nwkf1ph0000gn/T/git-reviewer/cache/prod/container.php on line 130 and defined in /Users/weaverryan/Sites/os/git-reviewer/vendor/knplabs/github-api/lib/Github/HttpClient/Builder.php:80

I don't have a good idea of how to fix this :) 

Cheers!

**Comment by OskarStark** [comment]
Any news here @Nyholm it would be cool to be able to give carsonbot some love and newer PHP

**Comment by Nyholm** [comment]
Let's drop the git-reviewer feature. It wasn't as well received as I thought.
